### ISSUE TITLE
Invalid geometries for certain number of clusters (e.g. 37)

### ISSUE THREAD

**Issue by alar0330** [PyPSA/pypsa-eur-sec#40] opened 2019-08-07 14:31 UTC
#### Issue
Some number of clusters (e.g. **37**) results in invalid geometries for clustered 'onshore_regions'.

#### Stack Trace

```console
(pypsa2) admin@cluster:~/Sandbox2/pypsa-eur-sec$ snakemake
```

```console
( ... )
[Wed Aug  7 13:24:04 2019]
rule build_temperature_profiles:
    input: resources/pop_layout_total.nc, resources/pop_layout_urban.nc, resources/pop_layout_rural.nc, /home/admin/Sandbox2/pypsa-eur/resources/regions_onshore_elec_s_37.geojson
    output: resources/temp_soil_total_elec_s_37.nc, resources/temp_soil_rural_elec_s_37.nc, resources/temp_soil_urban_elec_s_37.nc, resources/temp_air_total_elec_s_37.nc, resources/temp_air_rural_elec_s_37.nc, resources/temp_air_urban_elec_s_37.nc
    jobid: 12
    wildcards: network=elec, simpl=, clusters=37
TopologyException: Input geom 0 is invalid: Self-intersection at or near point 1.290313282832535 49.804757869024087 at 1.290313282832535 49.804757869024087
Traceback (most recent call last):
  File "/home/admin/Sandbox2/pypsa-eur-sec/.snakemake/scripts/tmpvo5q99lq.build_temperature_profiles.py", line 46, in <module>
    I = cutout.indicatormatrix(clustered_busregions)
  File "/home/admin/miniconda3/envs/pypsa2/lib/python3.7/site-packages/atlite/cutout.py", line 150, in indicatormatrix
    return compute_indicatormatrix(self.grid_cells(), shapes, self.projection, shapes_proj)
  File "/home/admin/miniconda3/envs/pypsa2/lib/python3.7/site-packages/atlite/gis.py", line 145, in compute_indicatormatrix
    area = d.intersection(o).area
  File "/home/admin/miniconda3/envs/pypsa2/lib/python3.7/site-packages/shapely/geometry/base.py", line 620, in intersection
    return geom_factory(self.impl['intersection'](self, other))
  File "/home/admin/miniconda3/envs/pypsa2/lib/python3.7/site-packages/shapely/topology.py", line 70, in __call__
    self._check_topology(err, this, other)
  File "/home/admin/miniconda3/envs/pypsa2/lib/python3.7/site-packages/shapely/topology.py", line 38, in _check_topology
    self.fn.__name__, repr(geom)))
shapely.errors.TopologicalError: The operation 'GEOSIntersection_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.multipolygon.MultiPolygon object at 0x7f37bb56cf98>
```

#### Environment (excerpt)
```shell
# Name                    Version                   Build  Channel
atlite                    0.0.2                     <pip>
cartopy                   0.17.0          py37h0aa2c8f_1004    conda-forge
fiona                     1.8.6            py37hf242f0b_3    conda-forge
gdal                      2.4.1            py37h5f563d9_5    conda-forge
geokit                    1.1.2                     <pip>
geopandas                 0.5.0                      py_2    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
glib                      2.58.3            h6f030ca_1001    conda-forge
libgdal                   2.4.1                h677e3de_5    conda-forge
numpy                     1.16.4           py37h95a1406_0    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
shapely                   1.6.4           py37h06cd6f9_1005    conda-forge
vresutils                 0.2.5                     <pip>
```

*pypsa-eur* commit:
```shell
(pypsa2) admin@cluster:~/Sandbox2/pypsa-eur$ git log -n 1 --oneline
07143fb base_network: Zero s_nom of under_construction lines
```

*pypsa-eur-sec* commit:
```shell
(pypsa2) admin@cluster:~/Sandbox2/pypsa-eur-sec$ git log -n 1 --oneline
eebac1b Deduct electric heating from electricity load profile
```

#### Description
It seems that invalid geometries (self-intersections?) appear **after** reading/writing from/to GeoJSON the clustered  `onshore_regions` data (e.g. I/O with `/resources/regions_onshore_elec_s_37.geojson` in case of 37 clusters) for **some** number of clusters. As mentioned, choosing 37 clusters results in this issues, whereas 38 clusters seems to work.

#### Test
Consider making an explicit check inside func `cluster_regions` in `scripts/cluster_network.py` (https://github.com/PyPSA/pypsa-eur/blob/07143fb2cd35fb2b85696b2eb7390a7e9bb46478/scripts/cluster_network.py#L168) for 
the validity of geometries before and after I/O:

```python
def cluster_regions(busmaps, input=None, output=None):
    if input is None: input = snakemake.input
    if output is None: output = snakemake.output

    busmap = reduce(lambda x, y: x.map(y), busmaps[1:], busmaps[0])

    for which in ('regions_onshore', 'regions_offshore'):
        regions = gpd.read_file(getattr(input, which)).set_index('name')
        geom_c = regions.geometry.groupby(busmap).apply(shapely.ops.cascaded_union)
        regions_c = gpd.GeoDataFrame(dict(geometry=geom_c))

        # CHECK GEOM BEFORE WRITE
        for t in regions_c.itertuples():
            if not t.geometry.is_valid:
                print("[AA] invalid geometry for '%s' before dumping GeoJSON @" % which, t.Index)
                break
        else: print("[AA] No invalid geometries for '%s' before dumping GeoJSON.." % which)

        regions_c.index.name = 'name'
        save_to_geojson(regions_c, getattr(output, which))

        # CHECK GEOM AFTER READ
        regions_c_loaded = gpd.read_file(getattr(output, which)).set_index('name', drop=True)
        for t in regions_c_loaded.itertuples():
            if not t.geometry.is_valid:
                print("[AA] invalid geometry for '%s' after loading GeoJSON @" % which, t.Index)
                break
        else: print("[AA] No invalid geometries for '%s' after loading GeoJSON.." % which)
```
Output:
```console
(pypsa2) admin@cluster:~/Sandbox2/pypsa-eur-sec$ rm ../pypsa-eur/resources/*37*
(pypsa2) admin@cluster:~/Sandbox2/pypsa-eur-sec$ snakemake
Building DAG of jobs...
Executing subworkflow pypsaeur.
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Unlimited resources: mem
Job counts:
        count   jobs
        1       cluster_network
        1       prepare_network
        2

[Wed Aug  7 14:21:25 2019]
rule cluster_network:
    input: networks/elec_s.nc, resources/regions_onshore_elec_s.geojson, resources/regions_offshore_elec_s.geojson, resources/clustermaps_elec_s.h5
    output: networks/elec_s_37.nc, resources/regions_onshore_elec_s_37.geojson, resources/regions_offshore_elec_s_37.geojson, resources/clustermaps_elec_s_37.h5
    jobid: 0
    benchmark: benchmarks/cluster_network/elec_s_37
    wildcards: network=elec, simpl=, clusters=37
    resources: mem=3000

INFO:pypsa.io:Imported network elec_s.nc has buses, carriers, generators, lines, links, loads, storage_units
INFO:pypsa.io:Exported network elec_s_37.nc has buses, loads, carriers, lines, generators, storage_units, links
[AA] No invalid geometries for 'regions_onshore' before dumping GeoJSON..
INFO:shapely.geos:Self-intersection at or near point 1.290313282832535 49.804757869024087
[AA] invalid geometry for 'regions_onshore' after loading GeoJSON @ FR0 0
[AA] No invalid geometries for 'regions_offshore' before dumping GeoJSON..
[AA] No invalid geometries for 'regions_offshore' after loading GeoJSON..
```

**Comment by nworbmot** [comment] 2020-05-07 12:53
This bug was fixed in https://github.com/PyPSA/pypsa-eur-sec/commit/8538233bba5d0c24f86e8c296198546657ca5d6b.
I can confirm all the details reported by @alar0330. Thank you for this excellent and detailed issue description!
The problem is caused by the onshore cluster bus region geometries.
These geometries are apparently invalid due to self-crossing or self-touching polygons.
These geometries are created by pypsa-eur/scripts/cluster_network.py but appear to be valid before being written to file, so it was not possible to fix the problem in PyPSA-Eur.
They are only valid after being read back in from file, as @alar0330 points out.
This seems to indicate some numerical issue relating to file reading and writing for geopandas.
The solution is to clean the geometries after being read in.
According to the advice [here](https://stackoverflow.com/questions/20833344/fix-invalid-polygon-in-shapely), [here](https://stackoverflow.com/questions/13062334/polygon-intersection-error-in-shapely-shapely-geos-topologicalerror-the-opera) and [here](https://shapely.readthedocs.io/en/latest/manual.html#object.buffer) the problem can be solved with `polygon = polygon.buffer(0)`.
cc @FabianHofmann @fneum @lisazeyen @euronion @eb5194

**Closed by nworbmot** 2020-05-07 12:53 UTC
